name = "dealbuster-admin-api"
compatibility_date = "2025-01-01"
main = "src/index.js"

[assets]
directory = "public"
binding = "ASSETS"
not_found_handling = "none"

[[kv_namespaces]]
binding = "KV"
id = "c67facdab9664a6189ecf536ddada140"

[vars]
TELEGRAM_ADMIN_ID = "715667303"
VAPID_PUBLIC_KEY = "BBpxbJXp8fXx1OG51wAiVjQ-QrWCqDd0eRyA6sxaw0MllG6RyPO-QHQfsig1VScCEdOfrzl6_vNfXuEBDIcBVaY"
VAPID_SUBJECT = "mailto:vakshay083@gmail.com"

[[durable_objects.bindings]]
name = "TG_POSTER"
class_name = "TgPoster"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TgPoster"]

[triggers]
crons = [
  "2,12,22,32,42,52 * * * *",
  "8,23,38,53 * * * *",
  "31 2,12 * * *",
  "0,5,10,20,25,30,35,40,50,55 * * * *",
  "14,44 * * * *"
]
