name = "dealbuster-admin-api"
compatibility_date = "2025-01-01"
main = "src/index.js"

[assets]
directory = "public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "KV"
id = "c67facdab9664a6189ecf536ddada140"

[triggers]
crons = [
  "2,12,22,32,42,52 * * * *",
  "5 */2 * * *",
  "31 2 * * *",
  "31 12 * * *"
]
